"""add_service_api_keys

Revision ID: 2312cebf85bb
Revises: ac3f0632be82
Create Date: 2025-12-20 20:14:25.382100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2312cebf85bb'
down_revision: Union[str, Sequence[str], None] = 'ac3f0632be82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('pub_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('mod_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_api_keys_key_prefix'), 'service_api_keys', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_service_api_keys_name'), 'service_api_keys', ['name'], unique=True)
    op.create_index(op.f('ix_service_api_keys_uuid'), 'service_api_keys', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_api_keys_uuid'), table_name='service_api_keys')
    op.drop_index(op.f('ix_service_api_keys_name'), table_name='service_api_keys')
    op.drop_index(op.f('ix_service_api_keys_key_prefix'), table_name='service_api_keys')
    op.drop_table('service_api_keys')
    # ### end Alembic commands ###
