"""add_expires_on_to_users

Revision ID: ac3f0632be82
Revises: bfba6d265aa7
Create Date: 2025-12-20 19:45:41.276111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac3f0632be82'
down_revision: Union[str, Sequence[str], None] = 'bfba6d265aa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('expires_on', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'expires_on')
    # ### end Alembic commands ###
